
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '2F7DED0151B2064FEF76F87476D33DDF'
    
_lr_action_items = {'STAR':([1,2,3,5,8,9,10,11,],[5,-6,-5,-4,5,5,5,-3,]),'RPAREN':([2,3,5,8,9,10,11,],[-6,-5,-4,11,-1,-2,-3,]),'EPS':([0,4,6,7,],[2,2,2,2,]),'CHAR':([0,4,6,7,],[3,3,3,3,]),'PLUS':([1,2,3,5,8,9,10,11,],[6,-6,-5,-4,6,-1,-2,-3,]),'LPAREN':([0,4,6,7,],[4,4,4,4,]),'MUL':([1,2,3,5,8,9,10,11,],[7,-6,-5,-4,7,7,-2,-3,]),'$end':([1,2,3,5,9,10,11,],[0,-6,-5,-4,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,6,7,],[1,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','run.py',80),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','run.py',95),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_PAREN','run.py',103),
  ('expr -> expr STAR','expr',2,'p_expr_STAR','run.py',107),
  ('expr -> CHAR','expr',1,'p_expr_char','run.py',122),
  ('expr -> EPS','expr',1,'p_expr_char','run.py',123),
]
