
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '29829CA5FF4B6920F6655B5F83AF3D58'
    
_lr_action_items = {'RPAREN':([2,4,5,7,8,9,],[-5,-3,-4,9,-1,-2,]),'CHAR':([0,1,2,3,4,5,6,7,8,9,],[2,2,-5,2,-3,2,2,2,2,-2,]),'PLUS':([1,2,4,5,7,8,9,],[6,-5,-3,6,6,6,-2,]),'LPAREN':([0,1,2,3,4,5,6,7,8,9,],[3,3,-5,3,-3,3,3,3,3,-2,]),'STAR':([1,2,4,5,7,8,9,],[4,-5,-3,4,4,4,-2,]),'$end':([1,2,4,5,8,9,],[0,-5,-3,-4,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,1,3,5,6,7,8,],[1,5,7,5,8,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','run2.py',73),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_PAREN','run2.py',77),
  ('expr -> expr STAR','expr',2,'p_expr_STAR','run2.py',81),
  ('expr -> expr expr','expr',2,'p_expr_mul','run2.py',85),
  ('expr -> CHAR','expr',1,'p_expr_char','run2.py',89),
]
