
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '64030EE493B9A45D2193D4952CB3C275'
    
_lr_action_items = {'STAR':([1,2,4,7,8,9,10,],[4,-5,-4,4,4,4,-3,]),'RPAREN':([2,4,7,8,9,10,],[-5,-4,10,-1,-2,-3,]),'CHAR':([0,3,5,6,],[2,2,2,2,]),'PLUS':([1,2,4,7,8,9,10,],[5,-5,-4,5,-1,-2,-3,]),'LPAREN':([0,3,5,6,],[3,3,3,3,]),'MUL':([1,2,4,7,8,9,10,],[6,-5,-4,6,6,-2,-3,]),'$end':([1,2,4,8,9,10,],[0,-5,-4,-1,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,5,6,],[1,7,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','run.py',88),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','run.py',103),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_PAREN','run.py',111),
  ('expr -> expr STAR','expr',2,'p_expr_STAR','run.py',115),
  ('expr -> CHAR','expr',1,'p_expr_char','run.py',129),
]
